"""Generate Rust's static entity table from the attributed WHATWG data."""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def generate() -> str:
    data = json.loads((ROOT / "typescript/src/entities.json").read_text())
    rows = []
    for name, value in sorted(data.items()):
        # Rust accepts Unicode escapes with braces, including control characters.
        encoded = "".join("\\u{" + format(ord(c), "x") + "}" for c in value)
        rows.append(f'    ("{name}", "{encoded}"),')
    return (
        "// Generated by tools/generate_rust_entities.py; see NOTICE.\n"
        "pub static NAMED: &[(&str, &str)] = &[\n" + "\n".join(rows) + "\n];\n"
    )


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    target = ROOT / "rust/src/entities_data.rs"
    expected = generate()
    if args.check:
        if target.read_text() != expected:
            raise SystemExit("Rust entity table is stale")
    else:
        target.write_text(expected)
